# Generated by Django 4.2.3 on 2023-07-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='posters/')),
                ('genres', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('year_release', models.IntegerField()),
                ('metacritic_rating', models.IntegerField()),
                ('runtime', models.IntegerField()),
            ],
        ),
    ]
